// Befehlskatalog mit den aktuell gültigen Befehlsnummern (Vorlage vom Nutzer bereitgestellt).
// Fachbegriff = offizielle Kurzbezeichnung, Erklärung = eigene, einfache Umschreibung für die Simulation,
// text = eigener, frei formulierter Formulierungsvorschlag (kein Original-Vordrucktext).

const BEFEHLS_KATALOG = [
  { nr: "1", titel: "Vorbeifahrt am EOA / Vorbeifahrt am Signal",
    hinweis: "Erlaubt die Vorbeifahrt an einem Halt zeigenden Signal oder am Ende der Fahrerlaubnis (EOA).",
    text: "Zug {zug} darf am Halt zeigenden Signal {von} vorbeifahren und bis {bis} weiterfahren." },
  { nr: "2", titel: "Weiterfahren nach TR / Weiterfahren nach Vorbeifahrt",
    hinweis: "Erlaubt die Weiterfahrt nach einer Teilrücknahme der Fahrerlaubnis oder nach einer Vorbeifahrt.",
    text: "Zug {zug} darf nach Vorbeifahrt an {von} bis {bis} weiterfahren." },
  { nr: "3", titel: "Verbleiben im Stillstand",
    hinweis: "Ordnet an, dass der Zug bis auf Weiteres im Stillstand verbleiben muss.",
    text: "Zug {zug} muss bei {von} bis auf Weiteres im Stillstand verbleiben: {grund}." },
  { nr: "4", titel: "Widerruf eines Befehls",
    hinweis: "Zieht einen zuvor erteilten Befehl zurück.",
    text: "Der zuvor an Zug {zug} erteilte Befehl wird hiermit widerrufen." },
  { nr: "5", titel: "Fahren mit Geschwindigkeitsbeschränkung",
    hinweis: "Ordnet für einen Abschnitt eine Geschwindigkeitsbeschränkung an.",
    text: "Zug {zug} darf zwischen {von} und {bis} höchstens {geschwindigkeit} km/h fahren." },
  { nr: "6", titel: "Fahren auf Sicht",
    hinweis: "Ordnet an, dass zwischen zwei Punkten auf Sicht gefahren werden muss.",
    text: "Zug {zug} muss zwischen {von} und {bis} auf Sicht fahren." },
  { nr: "7", titel: "Starten in SR",
    hinweis: "Erlaubt das Starten der Zugfahrt im ETCS-Betriebsmodus SR (Staff Responsible).",
    text: "Zug {zug} darf bei {von} im Modus SR starten." },
  { nr: "8", titel: "BÜ sichern",
    hinweis: "Ordnet an, einen Bahnübergang gesichert bzw. mit besonderer Vorsicht zu befahren.",
    text: "Zug {zug} muss den Bahnübergang zwischen {von} und {bis} mit höchstens {geschwindigkeit} km/h befahren." },
  { nr: "9", titel: "Fahren mit eingeschränkter Fahrstromversorgung",
    hinweis: "Informiert über eine eingeschränkte Fahrstromversorgung im befahrenen Abschnitt.",
    text: "Für Zug {zug} ist die Fahrstromversorgung zwischen {von} und {bis} eingeschränkt: {grund}." },
  { nr: "21", titel: "Einfahrt / Weiterfahrt",
    hinweis: "Erlaubt die Einfahrt in eine Zugmeldestelle oder die Weiterfahrt.",
    text: "Zug {zug} darf in/auf {von} einfahren bzw. bis {bis} weiterfahren." },
  { nr: "22", titel: "Ausfahrt aus dem Bf/Bft",
    hinweis: "Erlaubt die Ausfahrt aus dem Bahnhof bzw. Bahnhofsteil.",
    text: "Zug {zug} darf aus {von} ausfahren." },
  { nr: "23", titel: "Fahren auf dem Gegengleis",
    hinweis: "Erlaubt die Fahrt auf dem regelwidrigen Gleis (Gegengleis).",
    text: "Zug {zug} fährt auf dem Gegengleis von {von} bis {bis}." },
  { nr: "24", titel: "Zurückkehrende Fahrten",
    hinweis: "Regelt eine zurückkehrende Fahrt (z. B. Rückfahrt oder Nachschieben) bis zu einer bestimmten Stelle.",
    text: "Zug {zug} fährt bzw. schiebt nach von {von} bis {bis}." },
  { nr: "25", titel: "Weiterfahren sowie Ein- und Ausfahren vom Gegengleis",
    hinweis: "Erlaubt die Weiterfahrt sowie das Ein- und Ausfahren vom Gegengleis.",
    text: "Zug {zug} darf vom Gegengleis ab {von} bis {bis} weiterfahren bzw. ein-/ausfahren." },
  { nr: "26", titel: "Halten auf dem Gegengleis",
    hinweis: "Ordnet an, auf dem Gegengleis zu halten.",
    text: "Zug {zug} muss auf dem Gegengleis zwischen {von} und {bis} halten." },
  { nr: "27", titel: "LZB abschalten",
    hinweis: "Ordnet an, die LZB ab einer bestimmten Zugmeldestelle abzuschalten.",
    text: "Zug {zug} muss die LZB ab {von} abschalten." },
  { nr: "28", titel: "Wechsel ETCS-Level / Wechsel ETCS-Betriebsart",
    hinweis: "Ordnet einen Wechsel des ETCS-Levels oder der ETCS-Betriebsart an.",
    text: "Zug {zug} muss ab {von} das ETCS-Level bzw. die ETCS-Betriebsart wechseln: {grund}." },
  { nr: "29", titel: "Weiterfahrt signalgeführt / Weiterfahrt mit höchstens 40 km/h",
    hinweis: "Erlaubt die signalgeführte Weiterfahrt oder die Weiterfahrt mit höchstens 40 km/h.",
    text: "Zug {zug} darf ab {von} signalgeführt bzw. mit höchstens 40 km/h weiterfahren." },
  { nr: "30", titel: "Aus der LZB entlassen",
    hinweis: "Erlaubt, sich aus der LZB-Führung zu entlassen.",
    text: "Zug {zug} darf sich bei {von} aus der LZB entlassen." },
  { nr: "31", titel: "Rangieren über Ra 10 oder Einfahrweiche",
    hinweis: "Erlaubt eine Rangierfahrt über das Signal Ra 10 oder eine Einfahrweiche.",
    text: "Zug {zug} darf im Bereich {von} über Ra 10 bzw. die Einfahrweiche rangieren." },
  { nr: "32", titel: "Anhalten",
    hinweis: "Ordnet an, vor einer bestimmten Stelle anzuhalten.",
    text: "Zug {zug} muss vor {von} anhalten." },
  { nr: "33", titel: "gestörte LZB-Bk/ETCS-Bk",
    hinweis: "Informiert über eine gestörte LZB- oder ETCS-Blockstrecke im befahrenen Abschnitt.",
    text: "Zug {zug} muss bis zur gestörten Blockstrecke bei {von} {grund}." },
  { nr: "34", titel: "VMZ einstellen",
    hinweis: "Ordnet an, den Geschwindigkeitswert VMZ auf dem Führerstand einzustellen.",
    text: "Zug {zug} muss ab {von} VMZ auf {geschwindigkeit} km/h einstellen." },
  { nr: "95", titel: "Zusätzliche Anweisungen",
    hinweis: "Allgemeiner Befehl für zusätzliche Anweisungen, die durch keinen anderen Befehl abgedeckt sind.",
    text: "{grund}" },
];

function befehlByNr(nr) {
  return BEFEHLS_KATALOG.find(b => b.nr === nr);
}
