// Befehlskatalog – orientiert an der Systematik der Ril 408 (Fahrdienstvorschrift),
// Texte sind eigene, frei formulierte Kurzbeschreibungen für die Simulation.
// Jeder Eintrag hat: nummer, titel, hinweis (Ausfüllhilfe), textVorlage (Platzhaltertext fürs Befehlstextfeld)

const BEFEHLS_KATALOG = [
  { nr: "1", titel: "Vorbeifahrt an haltzeigendem Signal / Halt am Fahrerlaubnisende",
    hinweis: "Erlaubt die Vorbeifahrt an einem haltzeigenden Haupt-/Sperrsignal oder das Überfahren des Endes der Fahrerlaubnis (LZB/ETCS).",
    text: "Zug {zug} darf am haltzeigenden Signal {von} vorbei fahren und bis {bis} weiterfahren." },
  { nr: "2", titel: "Weiterfahrt nach Halt (Folgeauftrag)",
    hinweis: "Ergänzender Auftrag, wie nach einer Vorbeifahrt (z.B. nach Befehl 1) weiter verfahren werden soll.",
    text: "Zug {zug} darf nach Vorbeifahrt an Signal {von} bis {bis} auf Sicht weiterfahren." },
  { nr: "3", titel: "Abweichung von Fahrplan- oder Geschwindigkeitsangaben",
    hinweis: "Für Abweichungen von im Fahrplan/Buchfahrplan angegebenen Werten.",
    text: "Für Zug {zug} gelten von {von} bis {bis} abweichende Angaben: {grund}." },
  { nr: "4", titel: "Vorsicht wegen einer Gefahrenstelle",
    hinweis: "Warnung vor einer konkreten Gefahrenstelle im Streckenabschnitt.",
    text: "Zug {zug} muss zwischen {von} und {bis} wegen einer Gefahrenstelle mit besonderer Vorsicht fahren." },
  { nr: "5", titel: "Nachschieben eines Zuges",
    hinweis: "Regelt das Nachschieben, auch auf eingleisigen Strecken.",
    text: "Zug {zug} wird von {von} bis {bis} nachgeschoben." },
  { nr: "6", titel: "Gleis- oder Streckensperrung",
    hinweis: "Information über eine Sperrung, die die Fahrt betrifft.",
    text: "Für Zug {zug} ist der Abschnitt {von} bis {bis} gesperrt: {grund}." },
  { nr: "7", titel: "Geschwindigkeitsänderung / Langsamfahrstelle",
    hinweis: "Aufhebung oder Anordnung einer Geschwindigkeitseinschränkung.",
    text: "Zug {zug} darf zwischen {von} und {bis} höchstens {geschwindigkeit} km/h fahren." },
  { nr: "8", titel: "Bahnübergang sichern",
    hinweis: "Auftrag, einen technisch gestörten Bahnübergang gesichert zu befahren.",
    text: "Zug {zug} muss den Bahnübergang zwischen {von} und {bis} mit höchstens {geschwindigkeit} km/h und erhöhter Aufmerksamkeit befahren." },
  { nr: "9", titel: "Fahrt auf dem Gegengleis / Falschfahrt",
    hinweis: "Erlaubt die Zugfahrt auf dem regelwidrigen (Gegen-)Gleis.",
    text: "Zug {zug} fährt von {von} bis {bis} auf dem Gegengleis." },
  { nr: "10", titel: "Wechsel der Zuständigkeit",
    hinweis: "Regelt abweichende Wahrnehmung von Aufgaben zwischen Betriebsstellen.",
    text: "Für Zug {zug} übernimmt ab {von} eine andere Stelle die Zuständigkeit: {grund}." },
  { nr: "11", titel: "Zurücksetzen eines Zuges",
    hinweis: "Auftrag zum Zurücksetzen einer Zugfahrt.",
    text: "Zug {zug} darf von {von} bis {bis} zurückgesetzt werden." },
  { nr: "12", titel: "Auftrag anstelle eines Signalbegriffs",
    hinweis: "Ersetzt einen fehlenden/gestörten Signalbegriff (z.B. Zs1) durch einen Befehl.",
    text: "Zug {zug} erhält anstelle des Signalbegriffs an {von} den Auftrag: {grund}." },
  { nr: "13", titel: "Verständigung bei gestörter Kommunikationstechnik",
    hinweis: "Regelt die Verständigung, wenn Zugfunk/Kommunikationstechnik gestört ist.",
    text: "Für Zug {zug} gilt zwischen {von} und {bis} das Ersatzverfahren zur Verständigung: {grund}." },
  { nr: "14", titel: "Freitext für sonstige Aufträge",
    hinweis: "Allgemeiner Befehl für Fälle, die nicht durch Befehl 1-13 abgedeckt sind (inkl. Unterpunkte 14.1–14.35).",
    text: "{grund}" },
  { nr: "14.35", titel: "Rückzug eines Befehls",
    hinweis: "Zieht einen zuvor erteilten Befehl zurück.",
    text: "Der zuvor erteilte Befehl an Zug {zug} wird hiermit zurückgezogen." },
  { nr: "23", titel: "Fahren auf dem Gegengleis (Zusatzverfahren)",
    hinweis: "Community-Zusatzbefehl, wie im Bestandsarchiv verwendet.",
    text: "Zug {zug} fährt zwischen {von} und {bis} auf dem Gegengleis." },
  { nr: "26", titel: "Halten auf dem Gegengleis (Zusatzverfahren)",
    hinweis: "Community-Zusatzbefehl, wie im Bestandsarchiv verwendet.",
    text: "Zug {zug} hält zwischen {von} und {bis} auf dem Gegengleis." },
];

function befehlByNr(nr) {
  return BEFEHLS_KATALOG.find(b => b.nr === nr);
}
